### ISSUE TITLE
3.* wheel is  built for Python 2 too

### ISSUE THREAD

**Issue by bityob** [mitya57/secretstorage#12]
![image](https://user-images.githubusercontent.com/20026896/39184813-904097c0-47cd-11e8-82b7-cdb2d8a4e9ef.png)

Therefor, I think, when installing the package with pip, 

it tries to downloaded the 3.* version instead of lower one- 

```bash
user@ubuntu:~$ pip2 install SecretStorage
Collecting SecretStorage
  Using cached https://files.pythonhosted.org/packages/02/de/e4590cf025c714635637d4b2d19acfb1015f2d0c6cfe843b2b8f776ec819/SecretStorage-3.0.0-py2.py3-none-any.whl
SecretStorage requires Python '>=3.5' but the running Python is 2.7.14
```

Tested with pip version 9.0.3 and 10.0.1

I think building the wheel only for Python 3 will prevent pip to try installing the 3.* version.

See [here](https://packaging.python.org/tutorials/distributing-packages/#id75)

**Comment by mitya57** [comment]
This should be fixed now with version 3.0.1, please try again.

**Comment by inoks** [comment]
@mitya57 Same issue with the latest 3.0.1 version.

**Comment by mitya57** [comment]
@inoks Seems to work fine here:
```
$ pip2 install -v SecretStorage
...
    The package https://files.pythonhosted.org/packages/d8/d4/72bb1f525c325bdebf7a8df0071e0d9b64b2a48a27cac5f67712bae9fdc4/SecretStorage-3.0.1-py2.py3-none-any.whl#sha256=159a1ff82c57d692e1fa54ec9715eb7d9bc44f2cda7bdb00b108e22d8d54749c (from https://pypi.org/simple/secretstorage/) (requires-python:>=3.5) is incompatible with the pythonversion in use. Acceptable python versions are:>=3.5
    The package https://files.pythonhosted.org/packages/65/02/1f0d2a7b1221bc9a15f8b8d4de2c8ad8272c4d0af76cbdc72e2cf51d42e0/SecretStorage-3.0.1.tar.gz#sha256=819087ca89c0d6c5711692f41fb26f786af9dcc5bb89d567722a66edfbb2a689 (from https://pypi.org/simple/secretstorage/) (requires-python:>=3.5) is incompatible with the pythonversion in use. Acceptable python versions are:>=3.5
  Using version 2.3.1 (newest of versions: 1.0.0, 1.1.0, 2.0.0, 2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.2.0, 2.2.1, 2.3.0, 2.3.1)
...
```

Can you paste your output of the same command (with `-v`)?

**Comment by RonnyPfannschmidt** [comment]
it just broke a travis build here

**Comment by RonnyPfannschmidt** [comment]
https://travis-ci.org/ManageIQ/integration_tests/builds/370332122#L1036

**Comment by mitya57** [comment]
@RonnyPfannschmidt Your Travis job was run about 14 hours ago, while I released a fix only an hour ago. Please retry your job.

**Comment by inoks** [comment]
@mitya57 

```
Collecting secretstorage; sys_platform == "linux2" or sys_platform == "linux" (from keyring==10.5.1->-r requirements/development.txt (line 6))
  Downloading https://<...>/SecretStorage-3.0.1-py2.py3-none-any.whl
SecretStorage requires Python '>=3.5' but the running Python is 2.7.14
```

**Comment by RonnyPfannschmidt** [comment]
@mitya57  sorry my mistake, but also note that you shouldn't build universal wheels when they are in fact not, your wheel file-names claim py2 and py3 support, and certain versions of pip dont check further, in particular older ones if i recall correctly

**Comment by mitya57** [comment]
@inoks What are your versions of pip and setuptools?

I think you should either upgrade pip to `>=9`, or upgrade keyring to `12.0.2` which has the hack for older pip versions to pin SecretStorage.

**Comment by inoks** [comment]
@mitya57 I have pip 10.0.1 installed.

**Comment by mitya57** [comment]
@RonnyPfannschmidt Wheel updated, it now has only `py3` tag.

@inoks Please run pip with `-v` and show me the full log. Also try upgrading keyring to the latest version.
