### ISSUE TITLE
DBus authentication failure in jeepney doesn't get wrapped in SecretServiceNotAvailableException

### ISSUE THREAD

**Issue by Xiretza** [mitya57/secretstorage#13]
This epic was started by https://github.com/JonnyJD/musicbrainz-isrcsubmit/issues/119.

When jeepney (and in turn secretstorage) is used in a fakeroot environment, DBus authentication fails.
- This causes DBus to return "REJECTED EXTERNAL", triggering a `raise Exception()` [here](https://gitlab.com/takluyver/jeepney/blob/master/jeepney/integrate/blocking.py#L78). Or at least it would, if not for [this coding error](https://gitlab.com/takluyver/jeepney/merge_requests/4). Right now it raises the `ValueError` seen in the isrcsubmit issue above.
- [`dbus_init()`](https://github.com/mitya57/secretstorage/blob/master/secretstorage/__init__.py#L23) only checks for `KeyError` and `ConnectionError`, thus allowing the `Exception`/`ValueError` through.

`dbus_init` should probably check for this failure mode of jeepney too. Right now, that's a little difficult, with it either raising a generic `Exception` or `ValueError` - both of which are pretty much catch-alls. If you're fine with that, [\_\_init\_\_.py:44](https://github.com/mitya57/secretstorage/blob/master/secretstorage/__init__.py#L44) could be modified to just catch any `BaseException` and wrap that, which in my opinion is a valid use of a catch-all - it's just being wrapped in another exception, after all.

Alternatively, we could wait for [this other jeepney MR](https://gitlab.com/takluyver/jeepney/merge_requests/5) to go through, which raises a special exception in the case of an authentication failure. That could take quite a while though, I don't think that maintainer is particularly active and propagation might also take some time.

**Comment by mitya57** [comment]
I have just released version 3.1.0, which includes this change.
