### ISSUE TITLE
Python3 - object has no attribute 'send_and_get_reply' 

### ISSUE THREAD

**Issue by AlessandroZ** [mitya57/secretstorage#14]
Hi, 

I use your lib in my tool and during some tests, I had an error depending on which version of python I used. 
Everything works fine with: 
- Python 2.7.12
- SecretStorage: 2.3.1

However, it fails with python3: 
- Python 3.5.2
- SecretStorage: 3.0.1

Here is my traceback: 
```
[-] Traceback (most recent call last):
  File "/home/test/Linux/lazagne/softwares/wallet/libsecret.py", line 30, in run
    collections = list(secretstorage.collection.get_all_collections(bus))
  File "/home/test/.local/lib/python3.5/site-packages/secretstorage/collection.py", line 138, in get_all_collections
    for collection_path in service.get_property('Collections'):
  File "/home/test/.local/lib/python3.5/site-packages/secretstorage/util.py", line 59, in get_property
    (signature, value), = self.send_and_get_reply(msg)
  File "/home/test/.local/lib/python3.5/site-packages/secretstorage/util.py", line 41, in send_and_get_reply
    return self._connection.send_and_get_reply(msg)
AttributeError: 'BusConnection' object has no attribute 'send_and_get_reply'
```

Thanks a lot for your work.

**Comment by AlessandroZ** [comment]
Thanks for you answer. 

[Here](https://github.com/AlessandroZ/LaZagne/blob/master/Linux/lazagne/softwares/wallet/libsecret.py#L25) is how I initialized the bus. Session is retrieved from [here](https://github.com/AlessandroZ/LaZagne/blob/master/Linux/lazagne/config/homes.py#L82). 
You were right, it worked, if I replace this [line](https://github.com/AlessandroZ/LaZagne/blob/master/Linux/lazagne/softwares/wallet/libsecret.py#L30) by: 
```
connection = secretstorage.dbus_init()
collections = secretstorage.get_all_collections(connection)
```

However, my goal was to retrieve sessions of any users. For example, if you ran as root, it could still connect to your bus. 
It worked in python 2 doing like this: 
```
bus = dbus.bus.BusConnection(session)
collections = list(secretstorage.collection.get_all_collections(bus))
```

But I don't know how to do it with dbus_init because it seems deprecated to pass any arguments to dbus_init(). If you have an idea, it could be nice :)

**Comment by mitya57** [comment]
Sorry for the late reply.

For SecretStorage 3.x, try this:
```python
from jeepney.integrate.blocking import connect_and_authenticate
bus = connect_and_authenticate(session)
```

Please let me know how it works, maybe I will add an argument directly to `dbus_init` to support custom buses.

**Comment by AlessandroZ** [comment]
Hi, 

Thanks for your answer. I have made some tests but without success. If you want to test my tool to check the bug, it's really easy. 
```
git clone https://github.com/AlessandroZ/LaZagne.git
cd Linux
pip install -r requirement.txt
```
Then check it without sudo (it should work): 
`python3 laZagne.py wallet -libsecret -vv`

Then with sudo (should fail): 
`sudo python3 laZagne.py wallet -libsecret -vv`

With python 2.7, it works with and without sudo. 

All the code is [here](https://github.com/AlessandroZ/LaZagne/blob/master/Linux/lazagne/softwares/wallet/libsecret.py). 

Thanks for your help :)

**Comment by mitya57** [comment]
With the latest version of your repository, I get this error when running with sudo:
```python
Traceback (most recent call last):
  File "/tmp/LaZagne/Linux/lazagne/softwares/wallet/libsecret.py", line 44, in run
    bus = connect_and_authenticate(session)
  File "/home/dmitry/.local/lib/python3.6/site-packages/jeepney/integrate/blocking.py", line 76, in connect_and_authenticate
    auth_parser.feed(sock.recv(1024))
  File "/home/dmitry/.local/lib/python3.6/site-packages/jeepney/auth.py", line 25, in feed
    line, self.buffer = self.buffer.split(b'\r\n', 1)
ValueError: not enough values to unpack (expected 2, got 1)
```

That is a bug in Jeepney, it can be fixed with [this change](https://gitlab.com/takluyver/jeepney/merge_requests/4/diffs). After fixing it I get:
```python
Traceback (most recent call last):
  File "/tmp/LaZagne/Linux/lazagne/softwares/wallet/libsecret.py", line 44, in run
    bus = connect_and_authenticate(session)
  File "/home/dmitry/.local/lib/python3.6/site-packages/jeepney/integrate/blocking.py", line 78, in connect_and_authenticate
    raise Exception("Authentication failed: %r" % auth_parser.error)
Exception: Authentication failed: b'REJECTED EXTERNAL'
```

That means that D-Bus is rejecting the connection. It is because Jeepney is trying to authenticate as root, not as the original user.

The only way to fix it is monkey-patching Jeepney's `make_auth_external()` function. Try https://github.com/mitya57/LaZagne/commit/06aa6b4f3a9b2a2a79344cf92295c4c86ccfcf64 which should help.

**Comment by AlessandroZ** [comment]
Whouaa this is awesome, it works very well with your fix. Thanks a lot for your help. 
Have a nice day and thanks again :+1:

**Comment by takluyver** [comment]
Should Jeepney be authenticating with geteuid instead of getuid? I see that LaZagne is [calling seteuid()](https://github.com/AlessandroZ/LaZagne/blob/603c99f40a1920873ff44f18f4e78f71d728654e/Linux/lazagne/config/homes.py#L112). And it looks like the external information that DBus gets from the unix domain socket may actually be euid. If that's the case, we could avoid the need for monkeypatching.

**Comment by takluyver** [comment]
I made a (one character) pull request if anyone wants to test it: https://gitlab.com/takluyver/jeepney/merge_requests/7/diffs

**Comment by mitya57** [comment]
> I made a (one character) pull request if anyone wants to test it: https://gitlab.com/takluyver/jeepney/merge_requests/7/diffs

I can confirm that with that branch LaZagne works even when reverting commit AlessandroZ/LaZagne@c21018804786927d.

**Comment by takluyver** [comment]
Thanks! I'll merge it and aim for a new release of Jeepney soon.

**Comment by takluyver** [comment]
Jeepney 0.4 is now out, with that fix and several other changes ([release notes](https://jeepney.readthedocs.io/en/latest/release-notes.html).
