### ISSUE TITLE
content_type is always text/plain no matter what type is specified

### ISSUE THREAD

**Issue by grahampc** [mitya57/secretstorage#15]
The following code:

`connection = secretstorage.dbus_init()`
`collection = secretstorage.collection.get_default_collection(connection)`
`attributes = {'key': 'test'}`
`item = collection.create_item('test', attributes, b'\xff\xfe\xfd\xfc', replace=True, content_type='octet-stream')`
`print('content_type =', item.get_secret_content_type())`

prints
content_type = text/plain

It does not matter what value is passed as the 'content_type' argument, the content type of the stored item is always 'text/plain'. Is this a restriction of the keyring daemon as there is nothing in the code which explains this behaviour ?

**Comment by mitya57** [comment]
If your keyring daemon is GNOME Keyring then yes, it is a bug in that daemon.
