### ISSUE TITLE
Raise SecretServiceNotAvailableException if Gnome-keyring isn't installed

### ISSUE THREAD

**Issue by m3nu** [mitya57/secretstorage#18]
I believe this error should be caught in the `secretstorage` package.

https://github.com/borgbase/vorta/issues/235

**Comment by mitya57** [comment]
According to your stacktrace, it does exactly that:

    secretstorage.exceptions.SecretServiceNotAvailableException: The name org.freedesktop.secrets was not provided by any .service files

What is wrong?

**Comment by m3nu** [comment]
Right. Sorry. Then I will just test if the collection is available. Currently we just initialize DBus, but that's not enough to trigger the error.

```
class VortaSecretStorageKeyring(VortaKeyring):
    """A wrapper for the secretstorage package to support the custom keyring backend"""

    def __init__(self):
        """
        Test whether DBus and Gnome-Keyring are available.
        """
        self.connection = secretstorage.dbus_init()
        asyncio.set_event_loop(asyncio.new_event_loop())
        secretstorage.get_default_collection(self.connection)
```

One could just argue that the error should already show up on `secretstorage.dbus_init()`.

**Comment by mitya57** [comment]
Maybe I will change it in the future. But right now your fix is correct.
