### ISSUE TITLE
Add a link to secretstorage-setup

### ISSUE THREAD

**Issue by rsyring** [mitya57/secretstorage#2]
Notify keyring and SecretStorage projects to see if they are interested in linking to us.

**Comment by rsyring** [comment]
sorry, wrong project :(

**Comment by mitya57** [comment]
Indeed I can link to secretstorage-setup in the docs. Can you please create a pull request for that?

**Comment by mitya57** [comment]
Cross-linking this with level12/secretstorage-setup#1.
