### ISSUE TITLE
Need API for `unlock(pwd="password")`

### ISSUE THREAD

**Issue by wooparadog** [mitya57/secretstorage#21]
Hi, I've been using `gnomekeyring`, but it has since been deprecated. So I'm looking for an alternative, and this project seems most promising.

Script Using `gnomekeyring`:

```python
import gnomekeyring
import getpass
gnomekeyring.unlock_sync(None, getpass.getpass('Password: '))
```

The current api provided(`unlock()`) will not work if X is not running at all. So, an `unlock(password="")` would be appreciated.

**Comment by wooparadog** [comment]
never mind.. just found:

```python
import gi
gi.require_version('GnomeKeyring', '1.0')

import getpass
import gi.repository.GnomeKeyring
gi.repository.GnomeKeyring.unlock_sync(None, getpass.getpass('Password: '))
```

**Comment by mitya57** [comment]
I think libgnome-keyring used the method `UnlockWithMasterPassword` on interface `org.gnome.keyring.InternalUnsupportedGuiltRiddenInterface`.

For reasons that you can guess from the interface name, I am not going to implement that in SecretStorage.

If you are running gnome-keyring in headless mode, you can pass a password to it with an `--unlock` option, like described [here](https://github.com/jaraco/keyring#using-keyring-on-headless-linux-systems).
