### ISSUE TITLE
int_from_bytes depreciated error

### ISSUE THREAD

**Issue by devinnasar** [mitya57/secretstorage#29]
Hello,

secretstorage is a dependency of keychain, and that module attempts to load dhcrypto.py and util.py. Unfortunately, the version of SecretStorage on pypi caused the following errors:

```
/home/dnasar/.local/share/virtualenvs/opstools-kTlo0iS7/lib/python3.8/site-packages/secretstorage/dhcrypto.py:16: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
/home/dnasar/.local/share/virtualenvs/opstools-kTlo0iS7/lib/python3.8/site-packages/secretstorage/util.py:25: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
```

Is there a timeline on when a new release might be pushed? I noticed that these changes were recently corrected. Thanks!

**Comment by mitya57** [comment]
> Is there a timeline on when a new release might be pushed?

I have just released version 3.3.1 with this fix.
