### ISSUE TITLE
Setting schema not supported

### ISSUE THREAD

**Issue by abergmeier** [mitya57/secretstorage#31]
It seems to me like there is no way of setting `schema` metadata in Python. Is it only possible via C or did I miss something?

**Comment by mitya57** [comment]
The [Secret Service specification](https://specifications.freedesktop.org/secret-service/latest/) does not mention anything about schemas. Schemas are a GNOME-specific extension to the specification.

However, you can pass an attribute named `xdg:schema` when creating items. I just performed this small experiment and it looks like this attribute is understood by GNOME's secret-tool:

```python
>>> collection.create_item(label='Test item', attributes={'application': 'test', 'xdg:schema': 'me.mitya57.Schema'}, secret=b'123')
<secretstorage.item.Item object at 0x7fc516e1b670>
```

```bash
$ secret-tool search application test
[/org/freedesktop/secrets/collection/login/72]
label = Test item
secret = 123
created = 2021-02-20 18:03:18
modified = 2021-02-20 18:03:18
schema = me.mitya57.Schema
attribute.application = test
```
