### ISSUE TITLE
Remove dependency on dbus-python

### ISSUE THREAD

**Issue by snordhausen** [mitya57/secretstorage#4]
Hi!

We are using the secretstorage module in [one of our tools](https://github.com/ImmobilienScout24/afp-cli). Unfortunately, after the release of version 2.2.0, users of both MacOSX and Ubuntu Linux could not install it via `pip` any more. On both systems, this was caused by the newly introduced dependency on dbus-python, which failed to compile.

From your Travis tests I saw that I need to install `libdbus-glib-1-dev`, and this fixed the problem. I think, however, that the situation before the dependency was added was better:

Before dependency was added:
* works out of the box on Ubuntu & MacOSX
* in case it does not work, install the 'dbus-python' package (Ubuntu has it packaged, no need to use pip)

After the dependency was added:
* does not work out of the box on Ubuntu & MacOSX
* to install on Ubuntu, you need
 * a C-compiler with additional tools (which I happened to have)
 * the package libdbus-glib-1-dev (which might be called differently on other Linux distributions)

**Comment by mitya57** [comment]
I reverted that change. Do you want a new release?

Also, on Ubuntu I provide distro packages for SecretStorage, which depend on distro packages of dbus-python :)

**Comment by snordhausen** [comment]
Thanks! I already adjusted my workaround to only exclude version 2.2.0. So unless others have a problem, there's no need for a new release.

Unfortunately, distro-specific packages don't help in our case. We need to support users on Ubuntu, MacOS X and Windows, so installing via pip produces the least work for us.

**Comment by lmazuel** [comment]
Hi @mitya57,
You will make my day if you could do a new release :)

Thank you!

**Comment by mitya57** [comment]
@lmazuel A new release uploaded!
