### ISSUE TITLE
Migrate to supported alternative to pycrypto?

### ISSUE THREAD

**Issue by clarkbreyman-yammer** [mitya57/secretstorage#6]
Pycrypto has not been updated in 2 years with a fairly long list of open pull requests. There are alternatives: 
-- using pycryptodome (less desirable due to conflict with pycrypto install) 
-- using pycryptodomex and modifying the imports from Crypto to Cryptodomex
-- using cryptography and modifying more code

**Comment by mitya57** [comment]
Thanks for the suggestions, I will definitely look at them.

**Comment by mitya57** [comment]
I have now migrated to cryptography in Git. If you could test it, it would be much appreciated!

**Comment by lmazuel** [comment]
Hi @jaraco, since you directly use secretstorage in keyring, do you think you can check if the new dependency here is working with keyring?
I'm actually an really far indirect user of secretstorage (4 levels of dependencies...), I'm not sure I'm the right person to do that...

**Comment by jaraco** [comment]
I don't actually use Linux keyring on a regular basis. If I were to test this, I would have to start with a fresh VM and install the Python dependencies by hand and secret storage from Git... And I still wouldn't have any existing passwords to test. So I can't be of much help here.

**Comment by mitya57** [comment]
I have ran the python-keyring tests against the new source and they pass.

**Comment by lmazuel** [comment]
Hi @mitya57 
I don't think you made a new release here? Do you still need help for the testing?
Thanks!

**Comment by mitya57** [comment]
Hi @lmazuel, a new release uploaded!

**Comment by lmazuel** [comment]
Thanks a lot!
